[theme]
primaryColor = "#000000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#0d0d0d"
linkColor = "#2a65aa"
linkUnderline = false
borderColor = "#e5e5e5"
showWidgetBorder = true
baseRadius = "0.5rem"
font = "ui-sans-serif,-apple-system,system-ui,Segoe UI,Helvetica,Apple Color Emoji,Arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol"
codeFont = "ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace!important"
codeBackgroundColor = "#f9f9f9"
buttonRadius = "full"
headingFontSizes = ["36px", "24px", "20px"]
headingFontWeights = ["700", "600", "600"]


[theme.sidebar]
backgroundColor = "#f9f9f9"
secondaryBackgroundColor = "#f9f9f9"
